/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pointer to the schema against which this document should be validated
 */
export type Schema = string;

export interface Config {
    $schema?: Schema;
    /**
     * Directory path where the git repositories for the given account should be backed up
     */
    backupdir: string;
    /**
     * GitHub API information to backup all repositories the account has access to
     */
    githubapi: {
        /**
         * The GitHub API token that allows complete repo access to even clone private repositories
         */
        oauthtoken: string;
        /**
         * The GitHub account name
         */
        accountname: string;
    };
}
